### ISSUE TITLE
USERGUIDE.md is 404ing

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-cli-toolkit#43]
Small thing, but from the pypi page, when I click the link for the user guide, I get 404. The userguide here in gh seems to be fine.

https://pypi.org/project/hdx-cli-toolkit/USERGUIDE.md

**Comment by IanHopkinson** [comment]
Yes, this is actually a duplicate of #40! I think I decided fixing the link wasn't worth a whole release. Maybe once you finished finding issues I'll do a little documentation/bugfix release.

**Comment by IanHopkinson** [comment]
Resolved in #46
